### ISSUE TITLE
[Feature Request] set network proxy

### ISSUE THREAD

**Issue by szdytom** [LibreScore/app-librescore#11]
Allow user to set network proxy in Settings

**Comment by PeterNjeim** [comment]
Not sure why you'd need a proxy to use the app. Why not a system proxy?

**Comment by SealsRock12** [comment]
Currently, if you need this feature for only this app, you can use ProxyCap.

**Comment by PeterNjeim** [comment]
Closed since the feature wouldn't be used by most users

**Comment by Xmader** [comment]
similar issue: https://github.com/LibreScore/dl-librescore/issues/6

**Comment by Xmader** [comment]
It will be added in the next release.
