### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by Barmarel** [LibreScore/app-librescore#15]
When I click on download in the android app, I get 'Network Error'. But the Internet is fine.

**Comment by PeterNjeim** [comment]
Please do not ask for support on GitHub, GitHub is for code/project-related questions. Ask for support in the Discord server: https://discord.gg/DKu7cUZ4XQ.

To answer you anyways, it could either mean:
1. The server is down, try it again within the next 2 hours (restart the app before trying again)
2. Your device or network is blocking peer-to-peer (p2p) connections, try it again on another device or network, on a VPN, or ask someone else to download it for you on the Discord server
