### ISSUE TITLE
Legacy .MSI or .EXE installer support?

### ISSUE THREAD

**Issue by CSharperMantle** [LibreScore/app-librescore#2]
Is it possible to provide an installer in .MSI or .EXE format? The .MSIX format does not work on Windows PCs before Windows 10 1709 (aka Fall Anniversary Update).

Alternatively, targeting [MSIXCore](https://github.com/MicrosoftDocs/msix-docs/blob/master/msix-src/msix-core/msixcore.md) might be a solution to the issue, if possible.

**Comment by PeterNjeim** [comment]
Sorry for not noticing this issue, I am not watching this repository. We started targetting MSIXCore in version 1.0.1 when a discord user faced this problem. It his however noted that a dll error arose when installing on Windows 8.1. It could possibly work on Windows 10 versions older than the 1709 build, but I doubt it'd go older than that. Sorry for the delayed response.

**Comment by PeterNjeim** [comment]
Just as a funny note, version 1.0.1 came out before your issue, so you should've tested with the newest version before creating one, lol

**Comment by PeterNjeim** [comment]
You can unzip the MSIX file using something like 7-Zip. Then you can directly run the EXE file without installing it. Maybe that would work for your situation. Again, I don't know if it would work for older versions of Windows.

**Comment by srghma** [comment]
unzipping works

**Comment by PeterNjeim** [comment]
@CSharperMantle 
Windows 7+ support has been added in [v1.3.11](https://github.com/LibreScore/app-librescore/releases/tag/v1.3.11).

**Comment by CSharperMantle** [comment]
Thanks @PeterNjeim!

**Comment by jxu** [comment]
I get an issue "Windows cannot open .msix file". I'm on Windows 10 IoT Enterprise LTSC 21H2. 
Running from unzipped zip file worked fine.

**Comment by PeterNjeim** [comment]
Run the installer again but this time click No when PowerShell asks for administrative permissions. This will run the legacy installer. I tried to make the installer auto-detect if your Windows version could install MSIX, but it seems you're fell through the cracks, or possibly a group policy is blocking it
