### ISSUE TITLE
Getting "Network Error" every time I try to download anything

### ISSUE THREAD

**Issue by BloodRaven0** [LibreScore/app-librescore#22]
Happens with all songs and all formats. Both on Wifi and Mobile data. Any ideas what might be causing the problem?

Device: Poco X3 NFC
Android 10
App version: 2.0.26

Edit: just saw all the closed issues, will check the discord.

**Comment by PeterNjeim** [comment]
Support is only provided in the Discord server. GitHub is to share bug reports.
