### ISSUE TITLE
Error de red

### ISSUE THREAD

**Issue by Max6468** [LibreScore/app-librescore#29]
Al intentar descargar cualquier cosa, me sale el error de red. He desinstalado la app y la he vuelto a instalar y aun así no funciona, también reinicié mi ordenador

**Comment by sealsrock12** [comment]
El soporte técnico se proporciona en el servidor Discord, GitHub es solo para errores confirmados.
[![Discord](https://img.shields.io/discord/774491656643674122?color=5865F2&label=&labelColor=555555&logo=discord&logoColor=FFFFFF)](https://discord.gg/DKu7cUZ4XQ)

**Comment by Xmader** [comment]
> When trying to download anything I get the network error. I have uninstalled the app and reinstalled it and it still doesn't work, I also restarted my computer

translated by Google, for reference
