### ISSUE TITLE
Where is the download for Linux?

### ISSUE THREAD

**Issue by 99thGamer9** [LibreScore/app-librescore#3]
I reckon it's not very hard to just compile it for Linux

**Comment by SealsRock12** [comment]
Unfortunately, one of the plugins we use does not support linux.

**Comment by PeterNjeim** [comment]
Duplicate of #1. Please refrain from opening issues that already exist, instead, make a comment on the already-existing issue. Also, there were only 2 issues before you made yours lmao, hardly a chore to check. Maybe you weren't aware that it's standard not to open duplicate issues, that's fine, just please refrain from doing so in the future, in any repository, thanks.
