### ISSUE TITLE
App can't download official scores even if user has a pro + subscription

### ISSUE THREAD

**Issue by 8139david** [LibreScore/app-librescore#39]
Couldn't this functionality be added to the app? It would be very useful.

**Comment by sealsrock12** [comment]
No, this is not planned, just use the userscript with a Pro+ subscription

**Comment by Xmader** [comment]
It could be useful to have official score downloading in the app.

**Comment by PeterNjeim** [comment]
At the time it was closed official scores weren't available in the app

**Comment by YuenSzeHong** [comment]
> At the time it was closed official scores weren't provided in MSCZ format by MuseScore

maybe just have a mark for official scores and state only midi/mp3/pdf available?

**Comment by PeterNjeim** [comment]
Well MSCZ is now probably provided by MuseScore. We can possibly add an option to use the Pro+ subscription in the app

**Comment by PeterNjeim** [comment]
Most official scores (~96%) are PDF-only, meaning no MSCZ files are available. The latest version of the app now has official score download buttons grayed out
