### ISSUE TITLE
Not downloading on android

### ISSUE THREAD

**Issue by srghma** [LibreScore/app-librescore#4]
![Screenshot_20211215-202906](https://user-images.githubusercontent.com/7573215/146244445-a005d086-5a1a-4997-9c05-0a2642d25474.jpg)

**Comment by SealsRock12** [comment]
Tech support is provided in the discord server. 
[![Discord](https://img.shields.io/discord/774491656643674122?color=5865F2&label=&labelColor=555555&logo=discord&logoColor=FFFFFF)](https://discord.gg/DKu7cUZ4XQ)

**Comment by srghma** [comment]
@PeterNjeim said at discord

> This is due to an Android file permission issue. I've already fixed it, it'll be deployed in the next release

no, this error is present at v1.0.1

**Comment by SealsRock12** [comment]
Well that's because release v1.0.1 was released more than a month ago, and he said that on December 17

**Comment by PeterNjeim** [comment]
Don't close issues until they've been resolved in a deployed version of the app

**Comment by PeterNjeim** [comment]
Fixed in [v1.3.11](https://github.com/LibreScore/app-librescore/releases/tag/v1.3.11).
