### ISSUE TITLE
Can't install librescore

### ISSUE THREAD

**Issue by CapitaineCoco** [LibreScore/app-librescore#40]
When installing it, after accepting the license, this page comes up 
![image](https://user-images.githubusercontent.com/61109888/221939827-2b9cd5b4-30ec-4275-b29c-693aa890877c.png)
(i(m french so the page is in french)
and when i click install nothing appends. (or is it juste very very long?)

Can you help me fix this?

**Comment by PeterNjeim** [comment]
Exécutez à nouveau le programme d'installation, cette fois cliquez sur "Non" lorsque l'invite de l'administrateur apparaît. Il devrait lancer l'ancien programme d'installation.
