### ISSUE TITLE
Can you add support for jailbroken ios devices? (Doesn’t matter if it’s without gui)

### ISSUE THREAD

**Issue by ElioFegh** [LibreScore/app-librescore#41]

**Comment by sealsrock12** [comment]
Just curious, what are you planning to do with the MSCZ files on iOS? MIDI/PDF/MP3 downloads are available with the [userscript](https://github.com/LibreScore/dl-librescore#shortcut).

**Comment by ElioFegh** [comment]
Oh I’m sorry I didn’t see the userscript until now
