### ISSUE TITLE
window exe file said error

### ISSUE THREAD

**Issue by dlrjsdnr** [LibreScore/app-librescore#45]
when I click download button just off

**Comment by PeterNjeim** [comment]
Problem unclear, please speak your native language

**Comment by jianyi1995** [comment]
When I download files with the Windows application, server errors appear. My application version is 2.0.94.

![image](https://github.com/LibreScore/app-librescore/assets/12655555/55a33416-9461-4ab5-83b5-f1e69fc7eedd)

**Comment by PeterNjeim** [comment]
你好，Discord 服务器提供支持（应用程序的“关于”页面有一个链接）。 通常这个问题意味着 MuseScore 屏蔽了你的 IP，你应该在 Discord 服务器中分享你想要的歌曲的 URL，以便其他人可以为你下载。 谢谢， LibreScoreOn Jun 29, 2023 08:53, jianyi ***@***.***> wrote:
When I download files with the Windows application, server errors appear. My application version is 2.0.94.
