### ISSUE TITLE
LibreScore AppImage opens with a blank gui

### ISSUE THREAD

**Issue by crystalstorm466** [LibreScore/app-librescore#46]
Running Linux Mint 21.1 using Plasma KDE when trying to run the AppImage I just get a blank GUI and nothing pops up

**Comment by weep33** [comment]
The same here on Ubuntu 23.04 with wayland.

**Comment by PeterNjeim** [comment]
Version `2.0.92` working for me on Ubuntu 22.04.2 both Wayland and X11. I currently cannot test on other versions. Someone else got it working on Manjaro Gnome with Wayland as well, don't know the version number though. Are there any errors when you run the AppImage in a terminal?

**Comment by crystalstorm466** [comment]
Yes, I get this error:
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected character (at character 1)

**Comment by PeterNjeim** [comment]
Try this version: https://store3.gofile.io/download/9c4ef57d-4be1-40fa-a64f-e8140a1ad8c4/LibreScore.AppImage (this link will expire after a few days). If it still doesn't work, run `./LibreScore.AppImage --appimage-extract`, then `cd` into the `squashfs-root` folder it creates. `cd` into the `lib` folder. Try running `../librescore` and see if there are any error messages. You must be in the `lib` folder and use `..` to access the `librescore` binary, or else the dynamic linking won't work. Please get back to me with your results

**Comment by weep33** [comment]
This old version work for me: https://github.com/LibreScore/app-librescore/releases/tag/v2.0.70

**Comment by crystalstorm466** [comment]
Sorry for the long delay, Here is the error I get. 
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected character (at character 1)
...
^
`

And what @weep33 said v.2.0.70 works for me as well.

**Comment by PeterNjeim** [comment]
@weep33 did you try all the versions newer than v2.0.70 as well? Is v2.0.70 the latest version that works, or are there newer versions that also work

**Comment by jendrikw** [comment]
With 2.0.94:

`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value`

**Comment by PeterNjeim** [comment]
@jendrikw Is that the only error you receive, or are there more. Also, can you please test each version after v2.0.70 until you get a problem so I can diagnose which commit caused the issue. The others didn't get back to me. I didn't write the commits after v2.0.70 so I'm not totally sure what causes the issue

**Comment by COMBOhrenovke** [comment]
Can confirm, still present running latest release on Debian 12 (fuse2 installed). Neither does the gui function, nor did it create an icon for the program in the KDE menu, nor for the process running.

**Comment by PeterNjeim** [comment]
@COMBOhrenovke please don't reply to a thread without reading, I don't need any more confirmations, I need follow-ups to my requests

**Comment by RrOoSsSsOo** [comment]
On Arch Linux (update to 2023-08-01) after v2.0.70:

- v2.0.71 works
- v2.0.73 works
- v2.0.77 works
- v2.0.80 works

v2.0.86 (and >=) doesn't works!!

**Comment by PeterNjeim** [comment]
@RrOoSsSsOo Can you test this one (https://store4.gofile.io/download/2c4363d8-3d4a-426b-9042-d16f4f67713e/LibreScore.AppImage) for me please? Link will expire in a few days btw, tell me if you need more time

**Comment by RrOoSsSsOo** [comment]
> https://store4.gofile.io/download/2c4363d8-3d4a-426b-9042-d16f4f67713e/LibreScore.AppImage

Please provide me a public link fille, I can't download this one

**Comment by PeterNjeim** [comment]
@RrOoSsSsOo link expired, new one: https://store4.gofile.io/download/871f1877-c468-458e-8e5f-e8c12d9c6e8c/LibreScore.AppImage

**Comment by RrOoSsSsOo** [comment]
> new one: https://store4.gofile.io/download/871f1877-c468-458e-8e5f-e8c12d9c6e8c/LibreScore.AppImage

Same problem of >= v2.0.86, the screen (in dark theme) remain on this:
![image](https://github.com/LibreScore/app-librescore/assets/1734343/31d27199-7d4e-4cd8-a555-bf9c358d51f6)

**Comment by PeterNjeim** [comment]
Thanks for the confirmation. I'll diagnose it further tomorrow

**Comment by PeterNjeim** [comment]
@RrOoSsSsOo Hello again, download the following zip file and let me know which versions fail, thanks in advance

https://gofile.io/d/ruXEGP

**Comment by RrOoSsSsOo** [comment]
On my Arch

Work (UI is loaded):
2.0.80
2.0.81
2.0.82
2.0.83
2.0.84

Not Work:
2.0.85
2.0.86

**Comment by PeterNjeim** [comment]
@RrOoSsSsOo This one should work, let me know what happens. If it works, I'll release it as a new version soon: https://store10.gofile.io/download/b57b3b71-b1f2-418e-854b-e1fa137141e2/LibreScore.AppImage

**Comment by RrOoSsSsOo** [comment]
@PeterNjeim this version works perfectly! 👍

**Comment by PeterNjeim** [comment]
Fixed in version [`v3.0.7`](https://github.com/LibreScore/app-librescore/releases/download/v3.0.7/LibreScore.AppImage)
