### ISSUE TITLE
Oops! This score is unavailable in your country

### ISSUE THREAD

**Issue by Phloks** [LibreScore/app-librescore#48]
Hey is it possible to bypass scores which are locked because of your country?

![oops](https://github.com/LibreScore/app-librescore/assets/3481949/b4b4daac-1332-4259-aa24-ed89f6c55f04)

Like this here for example:

https://musescore.com/user/22584821/scores/4590826
https://musescore.com/user/22584821/scores/4304126
https://musescore.com/user/5205681/sheetmusic

Or is it possible to acess them via proxy?

It seems the are not entilery blocked, because its still shows the thumb and duration on the user-website.

**Comment by PeterNjeim** [comment]
You need to be in a country that has access to the score or use a VPN or proxy to a country that has access to the score
