### ISSUE TITLE
Add a feature to view scores by instrument (and ensemble)

### ISSUE THREAD

**Issue by chicken-tendies** [LibreScore/app-librescore#52]
I think this app is great, but this app should definitely have better search functionality.

This is why I think there should be a way to view scores by instrument, and/or ensemble. I have not been using this for very long, so it may already exist, but if not, it would be a great feature to have.

There could be a way to select the instruments that you want to filter by in 'Settings.' That would add a tab where there are the instruments you selected, and clicking one or more of the options will apply the filter to it.

I have attached an image below. It is very rough, but it is similar to what could be added. 

So, if you selected "Trumpet," "Clarinet," and "Drums" from a menu in 'Settings,' it would have buttons for all of those, and you could filter the search results by those instruments.

![UI Proposal](https://github.com/LibreScore/app-librescore/assets/74217006/047cbc74-37c1-448c-9957-ea80579c9dd4)

**Comment by PeterNjeim** [comment]
Indeed search filters have been considered in the past, but since this tool is for downloading and not browsing, we opted not to include it. Just for your knowledge, the app isn't functional currently, so we aren't updating it for the time being until we figure out how to fix it
