### ISSUE TITLE
Some music can be downloaded but some cannot

### ISSUE THREAD

**Issue by xiaoxi-ij478** [LibreScore/app-librescore#55]
This can be downloaded (MSCZ only):
<https://musescore.com/user/73797/scores/142975>
But this cannot:
<https://musescore.com/user/22400431/scores/4332546>

**Comment by PeterNjeim** [comment]
Works fine for me. If you're referring to a server error, that's could either be temporary or permanent, depending on if the issue is on LibreScore's side or your side. Please don't report server errors on GitHub, report them on Discord as it's a support request
