### ISSUE TITLE
Server error while downloading. (v5.0.2)

### ISSUE THREAD

**Issue by Ivan-Spoda** [LibreScore/app-librescore#57]
[RU]
Исправили ошибку сервера, молодцы, но она частично исправлена на данный момент, миди и мп3 не качает, только mscz... Тестировалось только на дройде, поэтому хз как на других будет...
Впн это не исправляет... Скрин с впн ниже..

[EN]
Can't download midi, mp3 due to server error, only mscz :(
Tested only on Android.
VPN doesn't fix this. Screenshot with VPN:
![Screenshot_2024-07-04-22-50-18-03_75211265db0cdfce854b01417d83dc03](https://github.com/LibreScore/app-librescore/assets/131347823/02a76fbb-bde7-45ca-a7ee-d7e926d1b70f)
:)

**Comment by PeterNjeim** [comment]
Server errors are a known issue. Please don't report server errors on GitHub, report them on Discord as it's a support request

Duplicate of: #49
