### ISSUE TITLE
MacOS will not open the Librescore app, saying it cannot scan for malware

### ISSUE THREAD

**Issue by Cybernetic-Fox** [LibreScore/app-librescore#59]
As in the title, I am on apple software (new laptop) and the latest version of Librescore app cannot be opened saying it's unable to do a scan on it.

**Comment by PeterNjeim** [comment]
I believe the next version of macOS is going to be changing how apps downloaded online can work. I'm not sure if this is related to that, but I'd like to learn more details about this. Please share your macOS version, and some screenshots or a screen recording of what's happening. Or, just type in step-by-step what you've done and what happens

**Comment by dimpurr** [comment]
Try go to System Settings.app - Privacy & Security - Security - Allow applications downloard from - Click the Button "Open Anyway"

**Comment by Cybernetic-Fox** [comment]
Thank you, sorry for not following up, but It does work now. I solved the issue on my own doing the same thing said above. Please mark this fixed! :)

**Comment by Cybernetic-Fox** [comment]
Thank you, sorry for not following up, but It does work now. I solved the issue on my own doing the same thing said above. Thankyou all anyways! :)
