### ISSUE TITLE
Downloads aren't working anymore

### ISSUE THREAD

**Issue by ALDOM6** [LibreScore/app-librescore#6]
Used to work before, now it doesnt?

**Comment by PeterNjeim** [comment]
Intermittent download issues are caused by a bug in the WebRTC implementation we are using: flutter-webrtc/flutter-webrtc/issues/759

**Comment by earlpeterg** [comment]
any updates to this?

**Comment by PeterNjeim** [comment]
@earlpeterg yeah it's been fixed about 1 minute ago in v1.3.15, lucky timing

**Comment by earlpeterg** [comment]
Thank you so much!
