### ISSUE TITLE
Make private scores viewable when linked to in the search bar

### ISSUE THREAD

**Issue by galeofperil** [LibreScore/app-librescore#61]
I use MuseScore to put together scores for my band, but I don’t want them to be publicly accessible, which unfortunately means they don’t show up in a search result.

Could there be a way to view private scores via the app, either through opening a local .mscz file or by opening a private score when it’s linked to directly in the search bar?

**Comment by PeterNjeim** [comment]
The app is a downloader and not a viewer. Because private scores can't be downloaded, they won't show up in the app
