### ISSUE TITLE
Windows Defender flags LibreScore.exe as Trojan

### ISSUE THREAD

**Issue by bauspanderu** [LibreScore/app-librescore#8]
I tried to run the v1.3.11 exe file, but Windows Defender immediately blocked it, saying it's "Trojan:Win32/Sabsik.FT.A!ml"

**Comment by PeterNjeim** [comment]
Just report the file as safe to Microsoft, hopefully they can sort it out

**Comment by PeterNjeim** [comment]
Although on my PC I'm not getting the warning. Considering you said *Windows Defender" and not "Windows Security", I can only assume you're using an outdated version of Microsoft's AV.

**Comment by bauspanderu** [comment]
Just to clarify, I've got Windows 11 and the newest version of Windows Security, I just call it Defender out of habit. Reported it to MS.

**Comment by PeterNjeim** [comment]
I have Security intelligence version 1.357.70.0, scanned the exe file, no threats found whennever I scan the 3 EXE files in the 1.3.11 release, could you share what version you have?

![image](https://user-images.githubusercontent.com/26418974/152486349-4aea8164-1863-4ae2-9bc9-1c3785a1754b.png)

**Comment by bauspanderu** [comment]
Nevermind, I did have an old version. Sorry to bother.

**Comment by PeterNjeim** [comment]
But does it detect it as a virus on the newer version? Or is it still detecting it as one, just want to get to the bottom of it

**Comment by bauspanderu** [comment]
I now have V. 1.357.70.0 too. It's totally fine now, no threats detected.
