### ISSUE TITLE
I Can't Install It on Windows 10

### ISSUE THREAD

**Issue by siayi** [LibreScore/app-librescore#9]
I Can't Install It on Windows 10. Stuck at 97%. With the following error message:

App installation failed with error message: error 0xC0020036: windows.licensing failed to start ClipSvc. Try again and contact the package publisher if the problem persists. (0xc0020036)

**Comment by PeterNjeim** [comment]
https://discord.com/channels/774491656643674122/776293233382653963/912533296230060053

**Comment by Xmader** [comment]
This issue shouldn't be marked as invalid since not everyone is on Discord,

**Comment by Xmader** [comment]
Copied from Discord

> seems like you accidentally deleted or disabled your ClipSvc service. Try downloading and running this registry file, then restart to see if it fixes the issue: https://www.tenforums.com/attachments/tutorials/92374d1469647609-services-restore-default-services-windows-10-a-client_license_service.reg
